project:
  type: website
  output-dir: docs

website:
  description: "Data Science 334 Semester Blogs"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Mason Zimmer's Data Visualization Blog"
  navbar:
    right:
      - about.qmd
      - icon: Linkedin
        href: https://www.linkedin.com/in/mason-zimmer-022875270/
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css

editor: visual

